---
output: word_document
---
Dear Editors of the Journal of Peace Research,

Thank you for the opportunity to revise and resubmit my manuscript "Two Sword Lengths Apart: Credible Commitment Problems and Physical Violence in Democratic National Legislatures".

I have done my best to incorporate the reviewers' very helpful suggestions, as well as your own, while keeping the manuscript within the Journal's 10,000 word limit (the revised text's word count is [GET]). The manuscript is much improved because of these suggestions.

It should be noted that I have also updated and further validated the legislative violence data set using additional searches detailed in the Online Appendix. Due to data availability on the covariates, the data set used in the statistical analyses now runs through 2012. Previously it ran through 2009. The results remain substantively the same however.

I have included two versions of the main manuscript. The first is a clean revised version. The second marks up all of the changes. My detailed responses to the suggestions are below. Page numbers referenced in the main text refer to the non-tracked changes version.

Please do not hesitate to contact me if you require more information or have other suggestions.

Kind regards,

--


-------------------

# Editor

> "While your ms. is in relatively good shape, I ask that the next version fully complies with JPR style."

I have attempted to fully conform the manuscript to JPR's style. I am happy to make additional changes as needed.

I have posted all of the data and replication files for this paper at:

- https://github.com/christophergandrud/leg_violence_paper1.

An overview of the contents of this repository is available at:

- https://github.com/christophergandrud/leg_violence_paper1/blob/master/README.md.

I also added a note after the main article text regarding the locations of these files. The URL is obscured in the revised manuscript to enable blind review.

> "I quite like Figure 2, however I would appreciate if you could change the color of the dots so they are distinguishable from one another when printed in grey scale."

I have put the dots on a grey scale.

> "Avoid the use of the term ‘recently’ in the abstract."

Removed.

> "Explain ‘disproportionate electoral outcomes’ in the abstract and earlier in the introduction."

I added a straightforward explanation of disproportionate electoral outcomes in the abstract and introduction.

> "P. 1: ‘Actual, sword fights…’ -> ‘Actual sword fights…’"

Corrected.

> "P. 2 and elsewhere: ‘paper’ -> ‘article’."

Replaced all 'paper' with 'article'.

> "P. 4: ‘a large increases’ -> ‘a large increase’"

Corrected.

> "P 5 and 7: please name hypotheses ‘H1’ and ‘H2’."

Added 'H1' and 'H2'

> "P. 6: ‘(Saideman, Lanoue and Stanton, 2002, 108)’ -> ‘(Saideman, Lanoue & Stanton, 2002: 108)’, here and throughout the ms."

> "P. 7: ‘(see Lijphart, 2007)’ -> ‘(Lijphart, 2007)’, here and throughout the ms."

Removed 'see' from all in-text citations.

> "P. 12: footnote 1 close to the bottom: which note does this refer to?"

Very sorry, this footnote should have been a description of the search terms/data gathering process for the legislative violence data set. This was mistakenly left out of the original submission due to a LaTeX compile issue. I have re-entered and expanded the information that should have been included in the main article (pages 12-13) and, in more detail, the Online Appendix (page 1).

> "P. 13: please name all six countries making up 60% of events."

I have mentioned the full list on page 13.  

> "P. 18: Models A4..A8 are, in my view superfluous and can be moved to the online appendix and mentioned only briefly in a footnote."

I have moved these models to the Online Appendix (Table II). I also moved the discussion of the variables in these models to the Online Appendix (pages 4-7).

> "P. 18: please consider adding past armed conflict as a control."

Thank you for this useful suggestion. I have included data on internal armed conflicts from the UCDP/PRIO Armed Conflict Dataset. The results from including all conflicts--internal and external--are similar, as there are very few interstate conflicts in the sample period. I have added the variable to the regression estimates tables. Results from current year conflict are shown. Lag and lead variables were also examined. Though the conflict variable (and its lags/leads) is sometimes significant, typically at the 10% level, the variable is overall not robustly significant. Its inclusion also does not alter the article's central findings. Nonetheless, given the substantive importance of this variable, we would certainly benefit from exploring the relationship between legislative violence and armed conflict in future research. This is mentioned in the conclusion.

> "Since one of the key contributions is the dataset, please do provide additional information on the data collection procedure (e.g. search algorithm?) and the coding (e.g. how did you separate between multiple events involving the same actors). Additional information should be included in the article, though more detailed descriptions may be relegated to the supplementary (online) file."

Unfortunately the footnote detailing the original data gathering process was accidentally omitted from the original version. It has been renetered as mentioned above. The replication materials listed above also contains a CSV file of primary sources on each violent incident (Data/violence_sources.csv) and short descriptions of the conflicts (Data/violence_incident_descriptions.md).

Largely subsequent to the original submission, I and three new research assistants completed a verification and update of the data using additional keyword searches of the Google News Archive, LexisNexis, NewsLibrary, NewsBank, NewsBank, Google, and YouTube (a surprisingly good source of information on the dynamics of legislative brawls). This work is primarily for a spin-off project, but I have incorporated all relevant changes to the data set used in this paper as well. The primary change was expanding the time period through 2012.

Regarding multiple events involving the same actors: by reading news accounts and viewing YouTube video footage of many of the brawls, it is clear that, for the purposes of this paper which concerns binary event occurrence, that each brawl can be considered a single event. Though brawl intensity varies over the course of the brawl as more or fewer legislators are involved, they tend to center around the same issue on the same day. Therefore, I treat each brawl as a single event per day. I added a note on this to page 1 of the Online Appendix. In future work, I will examine how brawls evolve once they start.

Finally, I added to the Online Appendix (page 2 and Figure 1) a discussion of why there are more observed violent incidents later in the sample. This may be predominantly the result of an increase in new democracies during that period, rather than measurement error caused by the electronic availability of news.

---------

# Joint issue from Reviewers 2 and 3

## Control over legislative procedures/resources vs. legislative policy outcomes?

> Both Reviewer 2 and 3 wonder whether legislators are concerned about legislative procedures or policy outcomes when deciding whether to brawl. Reviewer 2 mentions: "It seems like the theory, however, is more about being able to alter the rules used to establish policy. . . I wonder ... whether these are separate influences on the credible commitment mechanism (control of policy versus ability to alter the procedures), or whether they moderate the influence of the other". Reviewer 3 asks: "why are we assuming that legislatures are looking at the distribution of legislative resources and not legislative outcomes or even political outcomes?"

There seems to have been a slight confusion, likely due to poor wording on my part. The theoretical focus of this paper is on the ability to credibly commit to "peaceful bargaining outcomes". These outcomes can be either legislative rules or policies. A key reason for focusing on both is that they are highly intertwined theoretically and empirically.

An important component of the article's explanation of credible commitment problems is the control of legislative resources, broadly defined as both seats--i.e. legislative votes--and other resources such as committee appointments and agenda setting. The primary reason for defining legislative resources like this is that the set of actors who control legislative procedures and control legislative policy outcomes--bills that pass the legislature--are in practice often identical. Control of the procedures typically goes to the governing party/coalition and this group tends to have a majority or at least a plurality of seats. Control of the procedures enables agenda setting power that solidifies the governing party/coalition's power to control legislative outcomes, even if they do not control a majority of the seats. This is well understood in legislative studies as those who control the legislative agenda overwhelmingly control what bills (including legislative rule changes) are introduced to the floor to be voted on. These bills then have a very high probability of success (Tsebelis 2002, 93).

The inability to credibly commit to legislative rules means, by extension, that there is an inability to credibly commit to legislative policy outcomes. As such legislators, even those exclusively motivated by legislative outcomes, will be highly influenced in their behaviour by credible commitments about legislative rules.

I have tried to clarify key points from the above discussion in the text (pages 3-4 and especially the footnote 5 on page 3). Due to word count limitations, I have not discussed this point at length. However, I would be more than happy to develop the discussion further if the reviewers deem it necessary.

It's important to note that it becomes even more difficult to separate the two given that policy outcomes can affect control of future legislative resources. For example, a recent brawl in South Korea was over media ownership regulations. Allowing greater consolidation of media ownership, many feared, would politically advantage the main right-wing governing party by allowing increased control of media outlets by sympathetic news outlets. The US case study in the article is another example. Admitting Kansas to the US as a free state--a policy outcome--would also effectively end slave owning politicians' legislative power in the future, thus creating credible commitment problems. I would be happy to include an explicit discussion of this in the article, but haven't so far due to word count limits.

I have also moved the discussion of "unfair" legislatures (changed to disproportional control of legislative resources)--down to the Proportional Electoral Outcomes subsection. Hopefully, this helps clarify that for this mechanism the rules are indeed very important because they determine how big the potential power shift are and therefore how incredible commitments are. See below for a longer discussion.

All of this being said, as Reviewer 2 suggests, control over what passes in the legislature is not necessarily the same thing as who controls what bills actually become law, especially if there are non-legislative veto players (e.g. presidents or judiciaries). Non-legislative veto players may also limit the ability to change legislative rules, by for instance enforcing constitutional rules on how the legislature works. Perhaps, the wider political institutional environment impacts decisions to brawl.

To test this I included Henisz's (2004, updated through 2011) widely used measure of political constraints. It explicitly captures the feasibility of policy change given the number and polarisation of veto players. In additive models (shown in the main text, Table I) the variable is not statistically significant. In a new Interactions section of the Online Appendix (pages 8-13) I discuss some evidence that perhaps there is an interaction between political constraints and democratic age, such that more political constraints could help overcome credible commitment problems in new democracies. Current losers may be less worried that the current legislative winners can change the rules/implement policies that entrench power further in their favour.

It should be noted that the inclusion of government fractionalisation and single party government variables in the original text did also try to test the ease with which the majority can pass legislation. These variables were always statistically insignificant.

---------

# Reviewer 2

> "proportionality may influence the ability to easily pass policy, but it might not have an impact on the ability of the dominant group to alter the legislative procedures."

Please see above for my main comments/alterations in regards to procedures vs. policy outcomes.

At this point, I would like to clarify a confusion that I seem to have caused leading to the above sentence. Proportionality doesn't really have anything to do with how easy it is to pass policy overall, nor does it impact the dominant group's ability to alter legislative procedures. Knowing that electoral outcomes in one country are completely proportional and that they are very disproportional in another doesn't indicate anything about how easy policy change is in one vs. the other.

What it does do, and this is crucial for the theory, is indicate how much power could be gained if the system became more proportional. No power could be gained from making the completely proportional country more proportional and vice versa for the highly disproportional country.

Proportionality indicates how much each side wants to break/keep the status quo division of legislative resource. Proportionality therefore influences how credible their commitments to the status quo will be.

As mentioned above, I have tried to clarify this point by moving the main discussion of proportionality/power shifts to the Proportional Electoral Outcomes section.

> "Proportionality and democratic age are not themselves the cause of political violence, but are instead merely proxies for what is going on in the society as a whole, or as the author puts it, “large rapid demographic and party system shifts” (page 6). This might be the reason why a measure of societal differences (ethnic fractionalisation) is significant in some of the models (as noted on page 20)."

It may surely be (and the case study provides evidence that) societal factors can affect disproportionality and democratic stability, but this then causes credible commitment problems and ultimately legislative violence, rather than the societal changes affecting violence directly. 

It should be noted that there is typically not a direct correspondence between societal changes and changes with proportionality/democratic age. These are mediated by a host of factors (such as the electoral system, etc.). As such I do not expect proportionality/democratic age to be simple proxies for societal changes. Instead societal factors interact with a host of political institutional factors to alter disproportionality and democratic age.

Indeed, the large-n empirical results do not provide support for the above interpretation of ethnic fractionalisation (or self-expression). The expectation would be that the societal variables would at least be associated with violence in models without the proportionality/democratic age variables if they were the underlying cause of violence. This is not the case, as mentioned on page 18.  

I added a new section/table to the Online Appendix (pages 13-14) discussing models that have ethnic fractionalisation and other key variables list-wise added. In a model by itself, the variable is highly statistically insignificant. Estimates where ethnic fractionalisation is statistically significant (at the 10% level) are highly model dependent. Not only are they not found in models with only ethnic fractionalisation, but they are also absent when proportionality is included.  

Furthermore, the coefficient estimates for ethnic fractionalisation, regardless of level of statistical significance, are negative. I.e. more fractionalisation is associated with less violence. This is strongly counter to expectations. (I hazard to explain the direction of a non-statistically significant coefficient estimate, but my guess would be that countries with high ethnic homogeneity--e.g. South Korea, Japan, and Taiwan--could be driving this negative coefficient.) Given that (a) the estimates are not found in models without the disproportionality finding, (b) weakly statistically significant results are highly model dependent, and (c) run counter to expectations, it is reasonable to conclude that this paper has not found evidence that age of democracy and proportionality are merely proxies for ethnic fractionalisation when it comes to causing legislative violence.

That said, my prior is that Society causes -> Dem age/proportionality causes -> credible commitment problems causes -> legislative violence. This is a very interesting issue and surely occurs, as is demonstrated in the US case study. However, as with most investigations of societal phenomenon we need to distinguish between distal causes (e.g. societal factors and other issues such as factor endowments in the US case study) and proximal causes--disproportionality and democratic age. In this article it is not feasible to fully investigate the complex and interactive causal chain between distal and proximate causes. As discussed more below, societal factors often change very slowly, especially relative to the length of the sample available and interactive relationships mediate them and the proximate causes. Nonetheless, the US case study makes an important initial contribution to this work. I have also added a mention to the final paragraph in the Conclusion that more research is needed in this area.

> "Relatedly, I wonder whether this piece can actually say something about the timing of political violence. As it stands, democracy age and proportionality are relatively static, at least within a legislative session. Yet, the case study shows that it is the exogenous shocks that interact with the institutions to determine political violence; “three shocks that were largely exogenous from the national legislature” (page 10). It is my reading that the model does a good job of explaining the baseline level (or average) of political violence in a country, but a poor job of explaining why political violence occurs over time. Explaining how societal influences change in the context of legislative procedures would produce a dynamic account of legislative violence. You get at this partially by including measures of exogenous shocks like GINI and ethnic fractionalisation, but these are included additively rather than interactively."

This is a very interesting idea. In the Online Appendix (pages 8-13) I have included estimates from models that interact the two key political variables with societal factors and political constraints. There is some evidence that ethnic fractionalisation and a lack of political constraints heighten credible commitment problems in very new democracies leading to more violence. I briefly mention these findings in the main text as well (page 19), but not in detail because the substantive significance, given considerable overlap in expected values, is relatively weak. I would be happy to move these findings to the main text if you feel this is crucial.

Regarding timing: I think it is important to note that it is probably incorrect to consider the disproportionality and age of democracy variables as static relative to societal factors, especially over the period for which I have large-n data. Democratic age changes every year. Legislative majorities and proportionality change at each election and can change dramatically from election to election given relatively simple electoral rule changes. Societal factors such as ethnic fractionalisation, income inequality, and societal attitudes, on the other hand, typically change very slowly over 25 or so year periods. The processes behind ethnic and cultural shifts can take generations. The shocks that led to increasing disproportionality in the US case study, for example, materialised over almost half a century, even in a rapidly changing country with very high immigration and territorial expansion that is largely unparalleled in the contemporary period. Societal factors change so slowly that much of the data on them is updated infrequently. For example, Alesina et al.'s (2003) heavily used data (there are 71 Google Scholar citations of it from 2015 alone as of March 2015). This data is in fact completely static over the sample period.

Because of this, it would be very difficult to examine in a quantitative framework how *changes* in ethnic fractionalisation, etc *change* credible commitment problems over longer periods of time. As a viable alternative to future work before a much longer-time series is available, case study work, like the case study presented in the paper, which follows developments over about a 50 year period, could explore these issues.

> "I appreciate the empirical check for possible bias by limiting the sample to after 1990. However, I think more is needed to convince the reader that your method of data collection (assembling based on the Google News Archive) is picking up the universe of cases (or is in fact the best option available). Since some of the value of this project is in the creation of the original data set on legislative violence, it would be useful to describe this data collection in more detail. The fact that the author removes 22% of the sample by excluding the two most recent years (2010-2011) suggests that there is a bias for later years."

First, I discovered that a footnote detailing the search keywords did not show up in the original submitted version due to a LaTeX issue that I missed. I have now included an expanded discussion of this material in the Online Appendix (page 1).

Second, I and three research assistants have conducted additional keyword searches with LexisNexis, NewsLibrary, NewsBank, Google and YouTube (a surprisingly good source of videos of brawls) since the original data collection. This allows me to include observations through 2012 and improved our confidence that we have found close to the universe of incidents within our sampling frame.

Third, I agree that measurement bias in the later years could definitely be a possibility. This is a problem with virtually all digitally available information. However, perhaps the only other improvement on gathering this data would be to examine every country's legislatures printed record. This would be a considerable undertaking often involving accessing physical archives in well over 100 countries and many languages. This would be infeasible without considerable funding. Legislative records may in some regards be an inferior source. Brawls tend to be heavily reported on by the media. However, they are outside of normal legislative business and so many not be officially recorded.

Fourth, and perhaps most importantly, there are good reasons to believe that the temporal distribution of incidents in the data set does actually correspond to the population of legislative violence. The main reason for this is the temporal distribution of democratisation. The number of countries with elected legislatures has increased markedly over the observation period. The shift to democratization corresponds to the number of violent incidents observed in the sample. In a new section of the Online Appendix (page 2 and Figure 1) I plot the number of democracies in the sample per year and compare this to a plot of observed violent incidents per year. We see that there are on average many fewer incidents of violence in the period prior to about 1995. During this period there were relatively few democracies. Raw incidents of violence have increased as the number of countries with elected legislatures has increased. Clearly many of the new democracies in the sample are new democracies. As we found in the paper's empirics new democracies tend to have more violence.

> "I think that the empirics are competent done and I appreciate the extent of the robustness checks. My concern is that there is not enough variation in the dependent variable (especially by limiting the sample to smaller time periods), which is causing some of the “very large, highly unstable, and largely nonsenical coefficient estimates” (page 17). What can the author do to assuage these fears?"

In addition to the rare events logistic regression method that corrects bias created when there are a small number of 1's relative to 0's, it is important to note that the "very large, highly unstable, and largely nonsensical coefficient estimates" were only estimated for the political system type variable and in models with many highly correlated variables. The instability in the coefficient estimates likely has more to do with the high correlations between the covariates, which is common in this type of research (Achen 2002, Schrodt 2006) and, in the case of political system type, lack of variation on the covariate rather than the violence dependent variable. Political system rarely changes in the sample. The fact that variables that have more variation produce robustly stable coefficients bolsters the case that the issue the reviewer identifies is a problem with particular (and theoretically less interesting) covariates. While impeding our ability to examine if they affect violence, this does not really affect our ability to examine the other, much more theoretically interesting covariates. Other variables, primarily the new political constraints variable more directly address substantively interesting issues coming from political system type. I added a note on this to the discussion (moved to the Online Appendix, pages 4-5, due to word limit constraints).

Finally, it is important to reiterate that I have taken extensive additional steps to ensure that the data set includes all of the incidents of legislative violence in the sampling period. As such, I are confident that we have found close to all of the incidents in the sampling period.

> "One last nit-picky comment. I like the figures, but the use of jittered dots (rather than confidence intervals or some other alternative) needlessly increases the file size and caused my printer to choke!"

The plot now uses point ranges/ribbons to show the expected probabilities. This dramatically decreases the file size and increases legibility. Thank you for this suggestion.


---------

# Reviewer 3

> "My first issue with the manuscript comes from the seemingly normative view that violence in the legislature is an indication of poor functioning. . . While I generally agree with the author(s) intuition that we generally do not want violence in these bodies, I would also be careful about attributing that as a sign of good or bad governance. I suspect that we could easily come up with numerous examples where violence was needed to accomplish outcomes. . .  violence in the international system is argued as simply being another type of bargaining behavior and not as some sign of a poorly functioning system. Why could violence at the domestic level be seen in a similar light as simply continuing the bargaining process in a different manner?"

In many ways I completely agree with you that violence is a continuation of bargaining by other means and that a lack of violence does not necessarily indicate a well-functioning democratic institution. The theory I present in the first section (Understanding Legislative Violence) argues that indeed legislative violence is a continuation of bargaining by other means. This is a direct implication of using credible commitment theory to understand legislative violence. I've tried to highlight this further in the text (page 3).

I have also added a discussion in the Conclusion on the point that a lack of violence does not necessarily mean that a legislature is a well-functioning democratic institution. No violence in an autocratic legislature, for example, certainly does not indicate that the body is a well-functioning institution as judged against the commonly accepted democratic ideal of replacing violence with debate and discussion for reconciling conflicts. 

Furthermore, the manuscript discusses in the second section (Alternative Explanations) that a lack of violence in large governing majority legislatures may be either an indication that many legislators are included in the legislative process and can effectively bargain peacefully *or* that the governing majority is so powerful that it can take actions to quash violence before it happens.

One way that I have tried in the revised manuscript to empirically avoid conflating dynamics of flagrant non-democratic oppression leading to violence and a breakdown of democratic legislative bargaining causing brawls is to subset the sample so that it includes only democracies (i.e. country-years with Polity IV scores > 5). Originally, I included all countries that had elected multi-party legislatures as indicated by DPI LIEC scores > 5. Though there is considerable overlap in the two samples, they are different by about 200 country-years. In general, the results were substantively similar regardless.

Perhaps the (purely normative) point of disagreement that I have is that, while a lack of violence may not indicate well-functioning democratic institutions, a presence of violence *does* indicate that these institutions are not functioning according to the commonly held democratic ideal of enabling peaceful political contestation and conflict. I have emphasised this in the text: in the Abstract, Introduction, and most extensively, in the Conclusion. In the Introduction I have also tweaked the language at the beginning of the second paragraph to highlight that violence breaks *legislative scholars'* assumptions about how legislatures work, rather than being about good governance as such.

In sum, it is important to distinguish the article's two purposes:

1. The (primary) theoretical/empirical purpose: understand the conditions under which legislative bargaining in democratic legislatures reaches a point where one or more party feels that violence is a worthwhile tactic to pursue their bargaining objectives.

2. The (secondary, but motivational) normative purpose: highlight which of these findings could inform democratic institutional designs such that peaceful bargaining and competition between legislators will be more likely.

> "So why among all of the potential frameworks are we to believe that credible commitments are best?  Copious amounts of ink have been spilled talking about violence at the domestic level whether it be civil wars to protests to social movements.  I also suspect that there has been some investigation into pre-election violence among other democratic process related violence (perhaps extra-judicial killings). If they are not best that what are the alternatives that are equally plausible and why are they not utilized?"

The theoretical framework in this paper was strongly influenced by important recent contributions to understanding pre-election protest and violence, primarily the work of Wilkinson, 2006; Beaulieu and Hyde, 2008; Beaulieu, 2014. I have clarified this in the text (page 2). Protests and violence around elections is probably the most similar substantive area to legislative violence. These incidents also involve control and distribution of legislative resources in and control over future policy outcomes from democratic institutions. This previous research contends that election protests in particular are the result of bargaining breakdowns between governing elites and opposition groups. Factors that this literature proposes as causing bargaining breakdowns include credible commitment problems and misrepresentation of private information. My explanation of legislative violence builds on this theoretical work directly and makes an important contribution by understanding how legislative institutions affect these problems. I extensively discuss how credible commitment problems can lead to violence, especially in disproportionate legislatures and how democratic age can reveal information about opposing sides ability to credibly commit--i.e. helps ameliorate information asymmetries.

In addition, it should be noted that the second section (Alternative Explanations) does detail a number of alternative approaches to explaining violence in legislatures and is often specifically informed by the the legislative studies literature suggested to me in numerous conference presentations and discussions with colleagues. I then try to test these empirically. Discussion of additional variables examined for robustness (moved to the Online Appendix at the Editor's request) also involves alternative possible explanations.

Nonetheless, I certainly agree with you that an expanded discussion of the alternatives would improve the paper. To stay within the journal's word limit I have added a brief discussion of a recent expressive theory of legislative disruption (page 3 in the main article), theories of protest group organisation (Online Appendix, page 5), and protester/state relations (footnote 6 on page 3 in the main article). I would be happy to expand on these further in the text if the reviewer believes it is necessary, but it should be noted that the article is already right at the Journal's word limit.

> "I am not sure the author(s) definition of fair is useful. . . While I understand the intention, the problem is that there are so many unanswered questions that it becomes almost meaningless.  I do not mean that as negatively as it sounds but scholars have been arguing about the definition and meaning of fairness for centuries, so I so not see the utility of framing the paper in that literature (especially without really delving into it). Are they assuming that these conceptions of fairness are constant across time?"

This has indeed been a tricky issue for this paper through its development. You are correct that regardless of how specifically the term is defined in the paper, many readers bring considerable prior beliefs to their reading when the term 'fair' is used.

Overall, I feel that it is an issue of framing that can be ameliorated by using a different terminology and changing the paper's organisation. To avoid confusion with other and broader conceptualisations of fairness, I have replaced this term with a prediction that credible commitment problems are smaller when: 'seats in the legislature and legislative resources more generally, such as speaking time and committee appointments, proportionally correspond to voters’ support' (page 4). More verbose, but hopefully will avoid confusion. This is close to the Reviewer's suggestion that "The discussion of disproportional makes more sense and I think is the better way to approach and discuss the theory".

As such, 'fairness' has been entirely removed from the discussion of democratic age, and largely removed from the proportional electoral outcomes section. The paragraphs originally in the main part of the theory section that relate to proportionality have now been moved directly to the Proportional Electoral Outcomes subsection.

It should be noted that I have kept the proposition that legislatures where legislative resources closely correspond to electoral support are less likely to have violence because actors do care about fairness to some extent. Though not all actors and not in all times care about fairness to the same extent, the fact that many do is a very well established finding in the game theoretic and related experimental literature. This also corresponds to Marien's (2011) finding regarding the curvilinear relationship between electoral proportionality and citizen's political trust.

Importantly for this paper's theory it helps explain peaceful equilibria in highly proportional systems. Without the 'fairness equilibria' we would expect to see no difference in violence between more and less proportional legislatures. As you mention later, beneficiaries of increasing disproportionality in highly proportional systems might use violence to create disproportionate outcomes otherwise. If this was true then we would expect to see an insignificant proportionality variable--there is no difference in violence between proportional and more disproportional legislatures. However, we do not see this. I have added a footnote on this point to page 5.

Finally, I certainly do not assume that all actors will always view particular non-zero levels of disproportinality as 'fair'. However, I do believe that it is reasonable to view this issue probabilistically. As outcomes become closer to perfectly proportional more actors at more points in time will be more likely to view the outcomes as fair.

> "why are we assuming that legislatures are looking at the distribution of legislative resources and not legislative outcomes or even political outcomes?"

- Please see my comments above--in "Joint Concerns".

> "Would there not be a more dynamic process that takes into account deviations from expectations and not simply deviations from some pre-defined level?  The author(s) get at this a little with the old versus new democracy argument but it gets tangled up with the discussion of fairness.  I would simply talk about this as a more dynamic process and then the old versus new division seems a lot more intuitive."

- I have altered the discussion to reflect this (discussed above).

> "In addition, if these are linked then would there not be an interactive effect?"

- I have added estimates from a model interacting the proportionality and democratic age variables (Online Appendix, Table III, model 1). The interaction is weakly statistically significant (only the log(democratic age) term is significant at the 10% level). I hazard to interpret such a weakly statistically significant estimate, but marginal effects of the estimates (available upon request) suggest that the probability of violence is much lower in older democracies with high proportionality. This certainly fits the other findings in the paper and what we see in Figure 2 of the main text.

I am hesitant to overly interpret such a result in the article if published. As discussed on page 19 of the main text, it is well-established in the statistical literature that it can be difficult to find meaningful interactions in data sets with relatively small numbers of events. As such, more research is likely needed in the future when longer-time series become available. However, it should be noted that the weak evidence that does exist suggests that an interactive effect would strengthen support for the theory presented in the paper.

> "I am not sure what the case study does theoretically or empirically."

Thank you for this suggestion. Following your and the Editor's suggestion I have greatly strengthened the case for this case study on pages 9-10.

The case is useful for a number of reasons:

- It is a "typical case" (Seawright and Gerring 2008) in that it is a legislature in a new democracy with high disproportionality.

- The level of disproportionality changed considerably due to exogenous factors allowing us to make a within-case comparison: such that we can explore violence under both less and more disproportionate conditions in largely otherwise the same legislature. This helps address a question you raise below about the causal direction between disproportionality and violence. Of course this is one case, but it does demonstrate the plausibility of the causal chain where disproportionality causes violence.

- The case is drawn from outside the time period of the large-n sample. This helps us explore whether the hypotheses proposed in this paper are generalizable to other time periods.

- Furthermore, Reviewer 2 is very interested in understanding how societal factors may influence proportionality and democratic age and in turn their influence on brawls. For reasons that I discuss above, such as the general slowness of societal changes, this is very difficult to effectively investigate in the large-n work. Though the case study is by no means a definitive investigation of these complex relationships, it does provide an early glimpse into how they may work.

Another reason the case is theoretically interesting is related to your following question regarding Western cultural norms. Though it is difficult to gather information on violence in older legislatures, the case highlights that there are prominent examples of violence in Western democracies when they were younger--as the paper predicts. I have alluded to this on page 9, but would be happy to expand the discussion if requested.

Finally, I think some of the Reviewer's confusion regarding the applicability of the theory springs from a confusion about who the theory predicts will be violent. The theory (as discussed below) does not predict that only the current losers will use violence. Instead it anticipates that the current 'winners' or 'losers' may be violent as they both are subject to credible commitment problems.

> "Western democracies seem to stick out as the only democracies that do not experience violence.  Is this a cultural norm that has developed and being exported globally?  Obviously this is an empirical question but it is hard to ignore how western democracies stand out."

This is a tricky empirical issue. Western democracies are overwhelmingly older democracies. Therefore a lack of violence in them because of democratic age is observationally equivalent to a cultural/normative explanation. However, given the fact that violence did occur in older western democracies (e.g. US and UK), has occurred in newer democracies in the European Union such as Italy and Croatia, and there are incidents in Western sub-national legislatures--e.g. Alabama in 2007 (not included in the data set of national chambers)--it seems implausible that Western democracies are less violent for some inherent (essentialist) reason.

Could a non-violence norm have emerged in previously violent western democracies? Certainly, but then the question is why and how? Interestingly, the theory presented in the paper regarding the effect of democratic age on credible commitments provides an answer to this question. What could be thought of as a non-violence norm plausibly was created by learning over time whether commitments between legislators are credible.

This causal story, rather than a simple norm diffusion model, then also explains why the non-violence norm has not rapidly diffused to new democracies. Though perhaps the presence of such a global norm may speed the resolution of credible commitment problems in new democracies, the fact that violence still regularly occurs in new democracies indicates that credible commitment problems remain an issue.


> "is the violence a reaction to the disproportion or is the violence being used to create the disproportion?  The author(s) assume that it is those who do not have their fair share as acting out against it but why should we assume that?"  

I think the reviewer and I are actually in close agreement on this. As discussed in the theory section, violence may be *both* used by those who wish to have legislative resources more closely align with electoral support *and* by those who wish to preserve imbalances.  

One point of disagreement is that in highly proportional systems it does not appear--at least in this sampling period--that parties using violence to increase disproportionality is common. This is strongly supported by the empirical evidence where more proportional legislatures are less likely to have violence.

The US case study is also useful for exploring this point. It shows that disproportionality in the Senate increased for exogenous reasons. Violence then ensued because this disproportionality created credible commitment problems. Of course this is one case, but it demonstrates a plausible causal pathway from disproportionality to violence.

> "Could the violence be the source of the “unfairness.” In addition, why assume there is only one cause.  Could it not be the case that sometimes it is creating and others the cause in which case the question is when these happen?"

This is an interesting proposition. Though, I believe that the current analysis, as mentioned above, addresses this issue. The current paper proposes that violence can be used to maintain disproportionate outcomes. There is another possibility that is examined empirically: violence being used to create disproportionate outcomes in presently more proportional systems. If this was the case then the Lower Disproportionality variable would be statistically insignificant. I.e. their would not be a difference in brawls between proportionate and non-proportionate systems. However, we do not see this.

> "The author(s) assume that it is those who do not have their fair share as acting out against it but why should we assume that?"

I would argue that this is an incorrect reading of the paper. For example, the first paragraph of page 3 discusses why 'winners' and 'losers' would use violence. This is discussed throughout the theory section. For example on page 5: "Importantly, in the absence of credible commitments from the temporarily weak, the temporarily strong may use pre-emptive violence to prevent changes to the rules that distribute legislative resources in closer alignment with electoral support." The US case study shows that both sides broke peaceful bargaining outcomes (Sumner with his sexual imagery and Brooks by caning Sumner).

I realise a possible source of confusion may be that the wording regarding how disproportionality could incentivise violence from beneficiaries of disproportionality was unclear. I have changed this on page 5 ("They" to "The temporarily strong").

> "I think the author(s) need more fine grained data in order to determine who is instigating the violence to answer these questions but they seem critical as only one supports the theoretical argument."

Thank you for this suggestion. In fact, colleagues and I are actively deepening the detail of this data set so that we can understand the internal dynamics of specific brawls, including which side (those that would benefit from an increase or decrease in a correspondence between legislative resources and electoral support) 'started' a given brawl. Nonetheless, as you point out and as is discussed in the paper, either side could start a brawl with the ultimate cause being a credible commitment problem.

> "Finally, with so many zero cases and an event count, why not use a zero inflated negative binomial model?"

I examined the possibility of using zero inflated negative binomial regression. This was not in practice possible (using `zeroinfl` from the R pscl package). There are few country-years with more than 1 brawl (32). Most of these had two brawls, only 6 had 3 brawls. As zero inflated negative binomial regression uses a mixture model, there is likely not enough variation in the count part of the model to estimate it.

Furthermore, while I have strong hypotheses regarding whether or not violence will occur (i.e. the logistic part of the mixture model), I don't have any strong priors about why a country would have 2 as opposed to 1 brawl in a year. As such, though this was a helpful possibility to explore, zero inflated negative binomial regression appears to neither be estimable for this data or theoretically justified.
